name: CI/CD Workflow
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup python environment
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov -r requirements.txt

      # Run test cases with coverage
      - name: Run test with coverage
        run: |
          pytest --cov=src tests/ --cov-report=xml --cov-report=html
