name: CI/CD Workflow
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup python environment
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov -r requirements.txt

      # Run test cases with coverage
      - name: Run test with coverage
        run: |
          pytest --cov=src tests/ --cov-report=xml --cov-report=html
    
      #upload coverage report
        - name: Upload coverage report
            uses: actions/upload-artifact@v4
            with:
              name: coverage-report
              path: coverage.xml
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout thew repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Token }}

      # Build and Push docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.Docker_Hub_Username }}/gist-app:${{github.run_number}}
          file: ./Dockerfile
          
          
